# PYTORCH PARA DEEP LEARNING, PARTE UNO

### MATRICES


In [1]:
import numpy as np

In [2]:
matrix = [[1,2],[3,4]]
matrix

[[1, 2], [3, 4]]

In [4]:
matrix_numpy = np.array(matrix)
matrix_numpy

array([[1, 2],
       [3, 4]])

In [5]:
import torch


In [7]:
matrix_torch = torch.Tensor(matrix)
matrix_torch

tensor([[1., 2.],
        [3., 4.]])

#### Matrices definidas
##### Matrices "llenadas" de unos

In [9]:
mat_ones = np.ones((2,2))
mat_ones

array([[1., 1.],
       [1., 1.]])

In [10]:
mat_ones_torch = torch.ones((3,3))
mat_ones_torch

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##### Matrices "llenadas" de números randómicos

In [12]:
mat_random = np.random.rand(2,2)
mat_random


array([[0.97537347, 0.50403591],
       [0.6363683 , 0.95904755]])

In [13]:
mat_random_torch = torch.rand(4,4)
mat_random_torch

tensor([[0.8347, 0.8950, 0.2903, 0.2011],
        [0.3218, 0.8278, 0.3736, 0.4257],
        [0.3230, 0.9175, 0.2324, 0.4973],
        [0.4466, 0.0754, 0.8307, 0.4699]])

##### SEEDS para la reproducibilidad
Los seeds ayudan a "recuperar" los numeros randómicos que se generaron, sin usar los seeds se tendran cada vez numeros randómicos distintos.

#### En Numpy

In [17]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [15]:
#volvemos a usar random.rand con el seed(0)
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
#sin el seed
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

##### En Pytorch

In [19]:
#Usando seed
torch.manual_seed(0)
torch.rand(4,4)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185]])

In [20]:
#Usando seed
torch.manual_seed(0)
torch.rand(4,4)


tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185]])

In [21]:
#sin seed
#Usando seed
torch.rand(4,4)


tensor([[0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742],
        [0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320]])

#### Convirtiendo de NUMPY a TORCH
Matriz numpy a torch

In [26]:
mat= np.array(([[1,2],[3,4]]))
mat

array([[1, 2],
       [3, 4]])

In [27]:
type(mat)

numpy.ndarray

In [31]:
mat_torch = torch.from_numpy(mat)
print(mat_torch)

tensor([[1, 2],
        [3, 4]])


In [30]:
type(mat_torch)

torch.Tensor

In [36]:
mat_unos=np.ones((3,3), dtype=np.int8)
print(mat_unos)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [37]:
torch.from_numpy(mat_unos)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [39]:
mat2_unos = np.ones((3,3),dtype=np.int64)
mat2_unos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
mat2_torch = torch.from_numpy(mat2_unos)
print(mat2_torch)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


#### Convirtiendo de TORCH a NUMPY

In [47]:
torch_tensor = torch.ones(2,3)
print(torch_tensor)
type(torch_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Tensor

In [45]:
torch_to_numpy = torch_tensor.numpy()
torch_to_numpy


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [46]:
type(torch_to_numpy)

numpy.ndarray

### Operaciones Básicas Matemáticas en Tensores
#### Cambiando el tamaño del Tensor

In [53]:
ten = torch.ones(2,2)
print(ten)
print(ten.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [55]:
print(ten.view(4))
print(ten.view(4).size())

tensor([1., 1., 1., 1.])
torch.Size([4])


##### ADDITION (SUMA)

In [56]:
a = torch.ones(2,3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
b = torch.ones(2,3)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [58]:
c = a+b
print(c)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [59]:
c = torch.add(a,b)
print(c)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


#### Inplace Addition

<i>An in-place operation is an operation that changes directly the content of a given Tensor without making a copy. Inplace operations in pytorch are always postfixed with a _, like .add_() or .scatter_(). Python operations like += or *= are also inplace operations.</i>

In [61]:
print(c)
print("*"*10)
c.add_(a)
print(c)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
**********
tensor([[3., 3., 3.],
        [3., 3., 3.]])


##### SUBSTRACTION (RESTA)

In [64]:
a = torch.ones(4,4)
print(a)
b = torch.ones(4,4)
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [65]:
c = a-b
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Se aplicara <b>sub</b> para que se reste el valor <b>b</b> al valor de <b>a</b> pero este luego "recuperara" su valor inicial, esto por que no es <b>in-place</b>.

In [66]:
print(a.sub(b))
print("*"*20)
print(a)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
********************
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Ahora se aplicara la barra baja "_" para que sea <b>in-place</b> y pueda quedar el valor de a

In [67]:
print(a.sub_(b))
print("*"*20)
print(a)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
********************
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


##### MULTIPLICATION 

In [76]:
a = torch.ones(3,3)
b = torch.zeros(3,3)
c = a *b
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [78]:
print(torch.mul(a,b))
print("*"*15)
print(a)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
***************
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [79]:
a.mul_(b)
print(a)
print("*"*15)
print(a)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
***************
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


##### DIVISION

In [89]:
a = torch.ones(3,3)
b = torch.zeros(3,3)
c = b / a

print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [90]:
c = torch.div(b,a)
print(c)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [92]:
print(a.div(b))

print(a)

tensor([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [93]:
a.div_(b)
print(a)

tensor([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]])


##### Tensor Mean

In [99]:
a  = torch.Tensor([2,4,6,8])
a.dim()
#la dimension es 1, ya que es una lista simple

1

In [102]:
a.size()
# el tamaño es de 4, pues hay 4 valores dentro de la lista

torch.Size([4])

In [111]:
a.mean(dim=0)
# es solo una dimension (se empieza a contar desde 0 en este caso) y saca la media de esta dimension, o sea de toda la lista

tensor(5.)

In [107]:
a.mean(dim=1)
# da error pues no es mas de una sola dimension

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [108]:
b = torch.Tensor([[2,4,6,8],[1,3,5,7]])
b

tensor([[2., 4., 6., 8.],
        [1., 3., 5., 7.]])

In [109]:
b.size()


torch.Size([2, 4])

In [110]:
b.dim()

2

In [118]:
b.mean(dim=0) # la media de manera vertical: (2+1/2),(4+3/2)...

tensor([1.5000, 3.5000, 5.5000, 7.5000])

In [117]:
b.mean(dim=1) # la media de manera horizontal: (2+4+6+8/4),(1+3+5+7/4)

tensor([5., 4.])

##### Desviación Estandar 

In [120]:
b = torch.Tensor([1,2,3,4,5])
b.std(dim=0)

tensor(1.5811)