## PYTORCH

Proceso de aprendizaje:
* Forward pass
* Backpropagation
* Optimizacion

<br>
Usaremos tensores,
Recordando:

* Scalar
* Vector
* Matrix
* Tensor

La gradiente es un vector, tendra la magnitud y direccion de movimiento

## Pytorch tensor (y listas numpy) vs listas python
Si bien una lista de objetos numéricos es bastante parecido a un tensor de Pytorch (o una lista numpy), en realidad son completamente diferentes. Las listas de Python o las tuplas de números son
colecciones de objetos de Python que se asignan individualmente en la memoria. Los tensores PyTorch o las matrices NumPy, por otro lado, son vistas sobre (típicamente) bloques de memoria contiguos.
![](img/tensor_list.png)


In [2]:
import torch

In [3]:
torch.__version__

'1.1.0'

In [4]:
tensor_1 = torch.ones(2,2)
tensor_1

tensor([[1., 1.],
        [1., 1.]])

In [12]:
tensor_2=torch.Tensor(2,2)
tensor_2.uniform_(0,1)

tensor([[0.3953, 0.0776],
        [0.2544, 0.8850]])

In [15]:
tensor_2

tensor([[0.3953, 0.0776],
        [0.2544, 0.8850]])

In [16]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.3428, 0.3744],
        [0.5869, 0.3696]])

In [18]:
result =  tensor_2 + tensor_c
result

tensor([[0.7381, 0.4521],
        [0.8413, 1.2547]])

In [20]:
#imprime la forma del tensor
result.shape

torch.Size([2, 2])

In [21]:
reshaped = result.view(4,1)
reshaped

tensor([[0.7381],
        [0.4521],
        [0.8413],
        [1.2547]])

In [22]:
reshaped2 =  result.view(1,4)
reshaped2

tensor([[0.7381, 0.4521, 0.8413, 1.2547]])

In [30]:
points =  torch.tensor([[1.0,2.0],[3.0,4.0]])
points

tensor([[1., 2.],
        [3., 4.]])

In [31]:
points[0][1]

tensor(2.)

In [33]:
points[1][1]

tensor(4.)

## Tensors y Storage
Los valores se asignan en fragmentos contiguos de memoria, administrados por instancias de torch.storage. Un Storage es una matriz unidimensional de datos numéricos, es decir, un bloque contiguo de memoria que contiene números de un tipo dado. Tensor Storage es capaz de indexarse en ese almacenamiento utilizando un desplazamiento y zancadas por dimensión.
Múltiples tensores pueden indexar el mismo almacenamiento, incluso si se indexan en los datos de manera diferente. Sin embargo, la memoria subyacente solo se asigna una vez, por lo que la creación de vistas tensoras alternativas en los datos se puede hacer rápidamente, sin importar el tamaño de los datos administrados por la instancia de Storage.
![](img/tensor_storage.png)

In [60]:
'''
Veamos cómo funciona la indexación en el almacenamiento en la práctica con nuestros puntos 2D.
Se puede acceder al almacenamiento de un tensor determinado utilizando la propiedad
'''
prueba_storage = torch.tensor([[1.0,4.0],[2.0,1.0],[3.0,5.0]])
prueba_storage.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

Aunque el tensor informa que tiene 3 filas y 2 columnas, el almacenamiento es una matriz contigua de tamaño 6. En este sentido, el tensor simplemente sabe cómo traducir un par de índices en una ubicación en el almacenamiento.

## Stride
Para indexar en un almacenamiento, los tensores se basan en unos pocos datos que, junto con su almacenamiento, los definen inequívocamente: size (tamaño), storage offset (desplazamiento de almacenamiento) y strides (zancadas). El tamaño (o shape (forma) en NumPy) es una tupla que indica cuántos elementos en cada dimensión representa el tensor. El storage offset (desplazamiento de almacenamiento) es el índice en el almacenamiento correspondiente al primer elemento en el tensor. Stride es el número de elementos en el almacenamiento que deben omitirse para obtener el siguiente elemento a lo largo de cada dimensión.
![](img/tensor_strides.png)
<br>
<br>

* stride[0] = numero de saltos en el storage para llegar a la siguiente fila
* stride[1] = numeor de saltos para llegar a la siguiente columna

<br>
<br>
La mejor manera es visualizarlo en una transpuesta:
<br>


![](img/tensor_t_strides.png)

In [65]:
prueba_xd = torch.tensor([[1,2],[3,4],[5,6]])
prueba_xd

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [66]:
prueba_xd.stride()

(2, 1)

In [67]:
prueba_xd.t()

tensor([[1, 3, 5],
        [2, 4, 6]])

In [68]:
prueba_xd.t().stride()

(1, 2)

In [37]:
points.stride()

(2, 1)

Los strides (pasos) son una lista de enteros: el stride k representa el salto en la memoria necesario para pasar de un elemento al siguiente en la dimensión k del Tensor. Este concepto hace posible realizar muchas operaciones de tensor de manera eficiente.

In [49]:
prueba_stride = torch.Tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
prueba_stride

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [50]:
prueba_stride.stride()

(5, 1)

In [56]:
tr_prueba_stride = prueba_stride.t()
tr_prueba_stride

tensor([[ 1.,  6.],
        [ 2.,  7.],
        [ 3.,  8.],
        [ 4.,  9.],
        [ 5., 10.]])

In [55]:
tr_prueba_stride.stride()

(1, 5)