## PyTorch Fundmentals
#### Variables and Gradiantes

##### Variables
<ul>
<li>Una varibales "wrap" (envuelve) un tensor</li>
<li>Permite la acumulación de gradientes</li>
</ul>

In [1]:
import torch
from torch.autograd import Variable


In [2]:
a = Variable(torch.ones(2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# Esto no es una variable
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [4]:
b = Variable(torch.ones(2,2), requires_grad= True)
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
suma = a+b
suma

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [6]:
suma2 = torch.add(a,b)
suma2

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [7]:
multi = torch.mul(a,b)
multi

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

<b>tensors are equal to variables?</b>

<i>Think of tensors and variables as same thing. Variables are just wrappers for the tensors so you can now easily auto compute the gradients.

So if a tensor was batman…
A Variable would be batman but with his utility belt on…:grin:

Batman can do the job but if he has his utility belt on he’s got cool gadgets to use😉</i>
link: https://discuss.pytorch.org/t/what-is-the-difference-between-tensors-and-variables-in-pytorch/4914

##### Gradientes
¿Que significa <b>requires_grad</b>?

In [8]:
x = Variable(torch.ones(2), requires_grad= True)
x

tensor([1., 1.], requires_grad=True)

Ejemplo: <b>Se tiene la ecuación: y = 5(x+1)**2</b>

In [9]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

<b>Se reemplaza el valor de x por 1: y=5(1+1)**2, y= 5(2)**2, y=20</b>


In [11]:
y = 5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

Se lo reduce a un escalar (para que solo muestre un valor y no dos como se ve arriba)

In [12]:
o = (1/2)*torch.sum(y)
o
# o es la media de y

tensor(20., grad_fn=<MulBackward0>)

la derivada de o con respecto a x es <b>1/2*(10*(x+1))</b>

reemplazando los datos de x se tendra: <b>1/2*(10*(1+1)) = 1/2*(20) = 10</b>

In [13]:
o.backward()

In [14]:
x.grad

tensor([10., 10.])

In [16]:
#backward en detalle
o.backward(torch.FloatTensor([1.0,1.0]))
x.grad

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.