## DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ


#### Tensores
Los tensores son similares a los ndarrays de Numpy, en adición, estos pueden ser usados en en la GPU, para agilizar calculos computacionales. 

In [8]:
from __future__ import print_function 
import torch

In [9]:
##Vamos a construir un tensor de tamaño 5x3
x = torch.empty(5,3)
print(x)


tensor([[2.1019e-44, 6.7262e-44, 7.4269e-44],
        [6.3058e-44, 6.7262e-44, 7.8473e-44],
        [1.1771e-43, 6.8664e-44, 7.9874e-44],
        [8.1275e-44, 6.7262e-44, 6.7262e-44],
        [8.1275e-44, 7.2868e-44, 7.4269e-44]])


In [10]:
##Para construir un tensor con variables aleatorias
xx = torch.rand(4,4)
print(xx)

tensor([[0.1820, 0.9658, 0.5065, 0.0362],
        [0.0875, 0.7306, 0.0241, 0.6117],
        [0.7429, 0.1529, 0.5883, 0.3134],
        [0.8890, 0.3575, 0.1807, 0.5481]])


In [13]:
##Para constuir una matriz llena de ceros con tipo de datos Long
##Acerca de tipos de datos en Python: https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

xxx = torch.zeros(5,5,dtype=torch.long)
print(xxx)


tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [15]:
#Construir un tensor a partir de datos
xxxx = torch.tensor([5.5,3])
print(xxxx)

tensor([5.5000, 3.0000])
