In [2]:
import torch
import numpy as np

In [13]:
var1 = 2
var1_np = np.array(var1)

var2 = [2]
var2_np = np.array(var2)

var3 = [[1,2],[3,4]]
var3_np = np.array(var3)

In [14]:
var1_t = torch.from_numpy(var1_np)
var2_t = torch.from_numpy(var2_np)
var3_t = torch.from_numpy(var3_np)

In [16]:
print(var1_t)
print(var2_t)
print(var3_t)

tensor(2)
tensor([2])
tensor([[1, 2],
        [3, 4]])


In [17]:
print(type(var1_t))
print(type(var2_t))
print(type(var3_t))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [19]:
print(len(var1_t.shape))
print(len(var2_t.shape))
print(len(var3_t.shape))

0
1
2


## RANK, AXES and SHAPE

Son conceptos que se complementan, juntos son conectados.

### Rank 
Se refiere al numero de dimensiones que tiene el tensor

In [21]:
dd = torch.tensor([[1,2],[3,4],[5,6]])

In [22]:
dd.shape

torch.Size([3, 2])

In [24]:
print("Esto es el rank:",len(dd.shape))

Esto es el rank: 2


#### Reshaping

In [26]:
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
t.reshape(1,9).shape

torch.Size([1, 9])

## Pytorch tensors explained
Los tensorestorch ? son instancias de la clase tensor 

In [31]:
import torch
import numpy as np

## Tensor class

In [32]:
t = torch.Tensor()
type(t)


torch.Tensor

### Tensor attributes

In [34]:
print(t.dtype) #tipo de datos que estan dentro del tensor
print(t.device) #en que dispositivo esta alojado
print(t.layout) #como nuestro tensor esta alojado en nuestra memoria

torch.float32
cpu
torch.strided


In [37]:
'''
dtype, no se pueden sumar dos tensores con distintos tipos de 
variables dentro
'''
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.0,2.0,3.0])
t1+t2

RuntimeError: expected backend CPU and dtype Float but got backend CPU and dtype Long

## Opciones para crear un tensor usando datos

In [39]:
data = np.array([1,2,3,4])
type(data)

numpy.ndarray

In [42]:
data_tensor = torch.Tensor(data) #con la T mayuscula es el class constructor
print(data_tensor)
print(type(data_tensor))

tensor([1., 2., 3., 4.])
<class 'torch.Tensor'>


In [45]:
data_tensor_2 = torch.tensor(data) #con t minuscula es factory function(?)
print(data_tensor_2)
print(type(data_tensor_2))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [46]:
data_tensor_3 = torch.as_tensor(data) 
print(data_tensor_3)
print(type(data_tensor_3))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [47]:
data_tensor_4 = torch.from_numpy(data)
print(data_tensor_4)
print(type(data_tensor_4))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


## Creando tensores sin datos

In [56]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [49]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [52]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [53]:
torch.rand(2,2)

tensor([[0.1757, 0.1833],
        [0.1329, 0.3791]])