# Element wise tensor operations

In [1]:
import torch
import numpy as np

In [3]:
t1 = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
t2 = torch.tensor([[5,6],[7,8]],dtype=torch.float32)

In [5]:
t1 + t2 #la suma es un elemnt wise, devuelve una matriz del mismo tamaño

tensor([[ 6.,  8.],
        [10., 12.]])

In [6]:
t1 + 2 #lo mismo que: t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [10]:
t1 - 2 # t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [11]:
t1 / 2 #t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [12]:
t1 * 2 #t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

Por que es posible hacer lo de arriba, si estamos tratando con un escalar? porque estamos haciendo tensor broadcasting.

#### Broadcasting

In [13]:
# demostracion
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [14]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [16]:
#la manera larga(?)
t1 + torch.tensor(np.broadcast_to(2, t1.shape),dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

otro ejemplo de broadcasting, demostrando que esto no solo funciona con escalares

In [17]:
t1 = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
t2 = torch.ones([2],dtype=torch.float32)

In [19]:
print(t1.shape)
print(t2.shape)

torch.Size([2, 2])
torch.Size([2])


In [20]:
t1 + t2

tensor([[2., 3.],
        [4., 5.]])

El broadcasting tambien es posible tratando con diferentes dimensiones de tensores, como se mostro en la celda de arriba

### Comparison operations // tambien son element-wise

In [21]:
t =  torch.tensor([[0,5,7],[2,9,3],[8,8,1]],dtype=torch.float32)

In [25]:
t.le(5) #menores o iguales que 5

tensor([[1, 1, 0],
        [1, 0, 1],
        [0, 0, 1]], dtype=torch.uint8)

In [27]:
t.ge(5) #mayores o iguales que 5

tensor([[0, 1, 1],
        [0, 1, 0],
        [1, 1, 0]], dtype=torch.uint8)

In [29]:
t.gt(5) #mayores que 5

tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 1, 0]], dtype=torch.uint8)

In [31]:
t.lt(0) #menores que 5

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [33]:
t.eq(5) #iguales a 5

tensor([[0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)