### Creando tensores

In [5]:
import numpy as np
import torch

In [6]:
data = np.array([1,2,3])

In [9]:
t1 = torch.Tensor(data) #constructor
t2 = torch.tensor(data) #factory (?)
t3 = torch.as_tensor(data) #factory
t4 = torch.from_numpy(data) #factory

In [11]:
print(t1) #es flotante porque el constructor usa el tipo global default
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [14]:
#verificamos que el float es el default
torch.get_default_dtype()

torch.float32

In [15]:
#con los factories, no viene el default
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [17]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
#tambien se lo puede especificar
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Siendo todas las 3 anteriores similares (factories) cual se deberia usar, hay alguna diferencia entre ellas?

In [23]:
prueba = np.array([1,2,3,4])

In [24]:
p1 = torch.Tensor(prueba)
p2 = torch.tensor(prueba)
p3 = torch.as_tensor(prueba)
p4 = torch.from_numpy(prueba)

In [26]:
prueba[0] = 1
prueba[1] = 1
prueba[2] = 1
prueba[3] = 1

In [27]:
print(p1)
print(p2)
print(p3)
print(p4)

tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4])
tensor([1, 1, 1, 1])
tensor([1, 1, 1, 1])


* La diferencia entre los cuatro, es que los ultimos dos no crean copias en la memoria, estos estan enlazados al dato original.
* los primeros dos crean un espacio en la memoria

### Tipos de operacions en los tensores

* 1.- Reshaping tensors+
* 2.- Element-wise operations
* 3.- Reduce operations
* 4.- Access operations

### Reshaping tensors

In [43]:
import torch
t = torch.tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype=torch.float32)

In [44]:
t.size()

torch.Size([3, 4])

In [45]:
t.shape

torch.Size([3, 4])

In [46]:
len(t.shape)

2

In [47]:
#para saber cuantos componentes contiene:
#opcion 1
torch.tensor(t.shape).prod()

tensor(12)

In [48]:
#opcion 2
t.numel()

12

#### Maneras en las que puede ser cambiado el tensor, sin cambiar el rank

In [49]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [50]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [51]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [52]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [53]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [54]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [55]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [56]:
len(t.reshape(2,2,3))

2

### SQUEEZE Y UNSQUEEZE 

In [57]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [62]:
#elimina una dimension, elimina todos los axis (ejes) conn valor 1
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [61]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [65]:
#PRUEBA EXTRA SQUEEZE IGUAL A 1
#elimina una dimension, elimina todos los axis (ejes) conn valor 1
print(t.reshape(2,6,1))
print(t.reshape(2,6,1).squeeze())
print(t.reshape(2,6,1).squeeze().shape)

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [2.],
         [2.]],

        [[2.],
         [2.],
         [3.],
         [3.],
         [3.],
         [3.]]])
tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])
torch.Size([2, 6])


#### flatten

In [66]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [69]:
flatten(t) #reshape and squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [70]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

### Concatenando Tensores

In [71]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[5,6],[7,8]])

In [72]:
torch.cat((t1,t2))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [76]:
t1cat=torch.cat((t1,t2),dim=0)
print(t1cat)
print(t1cat.shape)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


In [77]:
t2cat = torch.cat((t1,t2),dim=1)
print(t2cat)
print(t2cat.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])
