## CNN FLATTEN OPERATION 

Para hacer el flatten necesitamos tener al menos dos ejes, por ejemplo las imagenes en blanco y negro pueden tener dos ejes (width=28, height=28)

In [1]:
import torch

Recordando: [2,1,28,28], hace referencia a que tenemos 2 batch size, 1 canal de color,  28 de height y 28 de width

In [3]:
#3 Imagenes 4x4
t1 = torch.tensor([[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]])
t2 = torch.tensor([[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]])
t3= torch.tensor([[3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3]])

In [4]:
t = torch.stack((t1,t2,t3))

In [7]:
t.shape #3 es el batch size

torch.Size([3, 4, 4])

In [8]:
#hay que añadir un eje del canal de color, vamos a decir que es grayscale
#lo añadimos con reshape
t = t.reshape(3,1,4,4)

In [9]:
t.shape

torch.Size([3, 1, 4, 4])

In [10]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [13]:
t[0] #la primera imagen

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [14]:
t[0][0] #el primer canal de color de la primera imagen

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [18]:
t[0][0][0] #la primera fila del primer canal de color de la primera imagen

tensor([1, 1, 1, 1])

In [19]:
t[0][0][0][0]#el primer pixel de la primera imagen del primer canal de color

tensor(1)

### vamos a aplicar el flatten

In [24]:
# 1 opcion
torch.flatten(t)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [25]:
#2 opcion
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [26]:
#3 opcion
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Estos metodos de arriba van bien, pero tienen el problema de hacer el flatten a todas las imagenes, no nos ayudará al implementarlo en nuestra cnn.

hay que hacer el flatten de manera individual por imagen

In [27]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [28]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])