## PYTORCH

Proceso de aprendizaje:
* Forward pass
* Backpropagation
* Optimizacion

<br>
Usaremos tensores,
Recordando:

* Scalar
* Vector
* Matrix
* Tensor

La gradiente es un vector, tendra la magnitud y direccion de movimiento

## Pytorch tensor (y listas numpy) vs listas python
Si bien una lista de objetos numéricos es bastante parecido a un tensor de Pytorch (o una lista numpy), en realidad son completamente diferentes. Las listas de Python o las tuplas de números son
colecciones de objetos de Python que se asignan individualmente en la memoria. Los tensores PyTorch o las matrices NumPy, por otro lado, son vistas sobre (típicamente) bloques de memoria contiguos.
![](img/tensor_list.png)


In [123]:
import torch

In [124]:
torch.__version__

'1.1.0'

In [125]:
tensor_1 = torch.ones(2,2)
tensor_1

tensor([[1., 1.],
        [1., 1.]])

In [126]:
tensor_2=torch.Tensor(2,2)
tensor_2.uniform_(0,1)

tensor([[0.0535, 0.6943],
        [0.2630, 0.7479]])

In [127]:
tensor_2

tensor([[0.0535, 0.6943],
        [0.2630, 0.7479]])

In [128]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.2234, 0.8773],
        [0.3344, 0.3589]])

In [129]:
result =  tensor_2 + tensor_c
result

tensor([[0.2769, 1.5716],
        [0.5974, 1.1068]])

In [130]:
#imprime la forma del tensor
result.shape

torch.Size([2, 2])

In [131]:
reshaped = result.view(4,1)
reshaped

tensor([[0.2769],
        [1.5716],
        [0.5974],
        [1.1068]])

In [132]:
reshaped2 =  result.view(1,4)
reshaped2

tensor([[0.2769, 1.5716, 0.5974, 1.1068]])

In [133]:
points =  torch.tensor([[1.0,2.0],[3.0,4.0]])
points

tensor([[1., 2.],
        [3., 4.]])

In [134]:
points[0][1]

tensor(2.)

In [135]:
points[1][1]

tensor(4.)

## Tensors y Storage
Los valores se asignan en fragmentos contiguos de memoria, administrados por instancias de torch.storage. Un Storage es una matriz unidimensional de datos numéricos, es decir, un bloque contiguo de memoria que contiene números de un tipo dado. Tensor Storage es capaz de indexarse en ese almacenamiento utilizando un desplazamiento y zancadas por dimensión.
Múltiples tensores pueden indexar el mismo almacenamiento, incluso si se indexan en los datos de manera diferente. Sin embargo, la memoria subyacente solo se asigna una vez, por lo que la creación de vistas tensoras alternativas en los datos se puede hacer rápidamente, sin importar el tamaño de los datos administrados por la instancia de Storage.
![](img/tensor_storage.png)

In [136]:
'''
Veamos cómo funciona la indexación en el almacenamiento en la práctica con nuestros puntos 2D.
Se puede acceder al almacenamiento de un tensor determinado utilizando la propiedad
'''
prueba_storage = torch.tensor([[1.0,4.0],[2.0,1.0],[3.0,5.0]])
prueba_storage.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

Aunque el tensor informa que tiene 3 filas y 2 columnas, el almacenamiento es una matriz contigua de tamaño 6. En este sentido, el tensor simplemente sabe cómo traducir un par de índices en una ubicación en el almacenamiento.

## Stride
Para indexar en un almacenamiento, los tensores se basan en unos pocos datos que, junto con su almacenamiento, los definen inequívocamente: size (tamaño), storage offset (desplazamiento de almacenamiento) y strides (zancadas). El tamaño (o shape (forma) en NumPy) es una tupla que indica cuántos elementos en cada dimensión representa el tensor. El storage offset (desplazamiento de almacenamiento) es el índice en el almacenamiento correspondiente al primer elemento en el tensor. Stride es el número de elementos en el almacenamiento que deben omitirse para obtener el siguiente elemento a lo largo de cada dimensión.
![](img/tensor_strides.png)
<br>
<br>

* stride[0] = numero de saltos en el storage para llegar a la siguiente fila
* stride[1] = numeor de saltos para llegar a la siguiente columna

<br>
<br>
La mejor manera es visualizarlo en una transpuesta:
<br>


![](img/tensor_t_strides.png)

In [137]:
prueba_xd = torch.tensor([[1,2],[3,4],[5,6]])
prueba_xd

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [138]:
prueba_xd.stride()

(2, 1)

In [139]:
prueba_xd.t()

tensor([[1, 3, 5],
        [2, 4, 6]])

In [140]:
prueba_xd.t().stride()

(1, 2)

In [141]:
points.stride()

(2, 1)

Los strides (pasos) son una lista de enteros: el stride k representa el salto en la memoria necesario para pasar de un elemento al siguiente en la dimensión k del Tensor. Este concepto hace posible realizar muchas operaciones de tensor de manera eficiente.

In [142]:
prueba_stride = torch.Tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
prueba_stride

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [143]:
prueba_stride.stride()

(5, 1)

In [144]:
tr_prueba_stride = prueba_stride.t()
tr_prueba_stride

tensor([[ 1.,  6.],
        [ 2.,  7.],
        [ 3.,  8.],
        [ 4.,  9.],
        [ 5., 10.]])

In [145]:
tr_prueba_stride.stride()

(1, 5)

In [146]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x.shape

torch.Size([4])

In [147]:
ej_uns1 = torch.unsqueeze(tensor_x,0)
ej_uns1,ej_uns1.shape

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [148]:
ej_uns2 = torch.unsqueeze(tensor_x,1)
ej_uns2,ej_uns2.shape

(tensor([[1],
         [2],
         [3],
         [4]]), torch.Size([4, 1]))

In [149]:
tensor_y = torch.tensor([[1,2],[3,4]])
tensor_y

tensor([[1, 2],
        [3, 4]])

In [150]:
tensor_y_uns1 = torch.unsqueeze(tensor_y,-3)
tensor_y_uns1,tensor_y_uns1.shape

(tensor([[[1, 2],
          [3, 4]]]), torch.Size([1, 2, 2]))

In [151]:
tensor_y_uns2 = torch.unsqueeze(tensor_y,2)
tensor_y_uns2,tensor_y_uns2.shape

(tensor([[[1],
          [2]],
 
         [[3],
          [4]]]), torch.Size([2, 2, 1]))

### Extra (Flatten,Reshape,Squeeze)

In [152]:
t = torch.tensor([[1,1,1],
                [2,2,2],
                [3,3,3],
                [4,4,4]],dtype=torch.float32)

In [153]:
t

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [154]:
t.size()

torch.Size([4, 3])

In [155]:
t.shape

torch.Size([4, 3])

In [156]:
# Rango del tensor:
len(t.shape)

2

In [157]:
'''
Para saber el numero de elementos dentro del tensor, multiplicamos
sus dimensiones
'''
torch.tensor(t.shape).prod()

tensor(12)

In [158]:
t.numel()

12

In [159]:
'''
Podemos cambiar la forma del tensor, tomando como relacion factores
del numero de elementos dentro del tensor.
Eje: 12 -> (3*4),(2*6),(1*12)
'''
t.reshape(4,3)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [160]:
t.reshape(3,4)

tensor([[1., 1., 1., 2.],
        [2., 2., 3., 3.],
        [3., 4., 4., 4.]])

In [161]:
t.reshape(2,6)

tensor([[1., 1., 1., 2., 2., 2.],
        [3., 3., 3., 4., 4., 4.]])

In [162]:
t.reshape(1,12)

tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]])

In [163]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)
print(len(t.reshape(1,12).shape))


tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]])
torch.Size([1, 12])
2


In [164]:
'''
Squeeze -> apretar
Reduce una dimension
'''

print(t.reshape(1,12).squeeze())
sq = t.reshape(1,12).squeeze()
print(len(sq.shape))

tensor([1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.])
1


In [165]:
print(sq.unsqueeze(dim=0))
# lo de abajo es lo mismo que lo de arriba
#print(torch.unsqueeze(sq,0))
#Se recupera una dimension
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)
print(len(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape))


tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]])
torch.Size([1, 12])
2


#### Entendiendo flatten

In [166]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [167]:
t, flatten(t)

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.]]),
 tensor([1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]))

In [168]:
t, t.reshape(1,12)

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.]]),
 tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]]))

In [169]:
flatten(t).shape,t.reshape(1,12).shape

(torch.Size([12]), torch.Size([1, 12]))

### Continuando

In [170]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x, torch.unsqueeze(tensor_x,1),torch.unsqueeze(tensor_x,1).shape

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]), torch.Size([4, 1]))

### Numpy

In [171]:
import numpy as np

In [172]:
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[ 0.0498,  0.0392],
        [-0.3432, -2.3150]], dtype=torch.float64)

### Representamos datos con Tensores

In [173]:
from_numpy.mean()

tensor(-0.6423, dtype=torch.float64)

In [174]:
torch.mean(from_numpy)

tensor(-0.6423, dtype=torch.float64)

In [175]:
print(from_numpy)
print(torch.mean(from_numpy,dim=0)) #media acorde a columnas
print(torch.mean(from_numpy,dim=1)) #media acorde a filas

tensor([[ 0.0498,  0.0392],
        [-0.3432, -2.3150]], dtype=torch.float64)
tensor([-0.1467, -1.1379], dtype=torch.float64)
tensor([ 0.0445, -1.3291], dtype=torch.float64)


In [176]:
print(from_numpy)
print(torch.std(from_numpy,dim=0)) #Desviacion estandar acorde a columnas
print(torch.std(from_numpy,dim=1)) #Desviacion estandar acorde a filas

tensor([[ 0.0498,  0.0392],
        [-0.3432, -2.3150]], dtype=torch.float64)
tensor([0.2779, 1.6647], dtype=torch.float64)
tensor([0.0075, 1.3943], dtype=torch.float64)


In [177]:
torch.save(from_numpy,'tensor.t') #lo guardo como tensor.t

In [178]:
load = torch.load('tensor.t')

In [179]:
load

tensor([[ 0.0498,  0.0392],
        [-0.3432, -2.3150]], dtype=torch.float64)

### Pandas

In [180]:
import pandas as pd

In [181]:
path = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(path)

In [182]:
dataframe

Unnamed: 0      ID                  Name  Age  \
0               0  158023              L. Messi   31   
1               1   20801     Cristiano Ronaldo   33   
2               2  190871             Neymar Jr   26   
3               3  193080                De Gea   27   
4               4  192985          K. De Bruyne   27   
5               5  183277             E. Hazard   27   
6               6  177003             L. Modrić   32   
7               7  176580             L. Suárez   31   
8               8  155862          Sergio Ramos   32   
9               9  200389              J. Oblak   25   
10             10  188545        R. Lewandowski   29   
11             11  182521              T. Kroos   28   
12             12  182493              D. Godín   32   
13             13  168542           David Silva   32   
14             14  215914              N. Kanté   27   
15             15  211110             P. Dybala   24   
16             16  202126               H. Kane   24   
17             17  194765          A. Griezmann   27   
18             18  192448         M. ter Stegen   26   
19             19  192119           T. Courtois   26   
20             20  189511       Sergio Busquets   29   
21             21  179813             E. Cavani   31   
22             22  167495              M. Neuer   32   
23             23  153079             S. Agüero   30   
24             24  138956          G. Chiellini   33   
25             25  231747             K. Mbappé   19   
26             26  209331              M. Salah   26   
27             27  200145              Casemiro   26   
28             28  198710          J. Rodríguez   26   
29             29  198219            L. Insigne   27   
...           ...     ...                   ...  ...   
18177       18177  238550             R. Roache   18   
18178       18178  243158          L. Wahlstedt   18   
18179       18179  246243           J. Williams   17   
18180       18180  221669              M. Hurst   22   
18181       18181  245734              C. Maher   17   
18182       18182  246001               Y. Góez   18   
18183       18183   53748         K. Pilkington   44   
18184       18184  241657             D. Horton   18   
18185       18185  243961              E. Tweed   19   
18186       18186  240917          Zhang Yufeng   20   
18187       18187  240158             C. Ehlich   19   
18188       18188  240927            L. Collins   17   
18189       18189  240160            A. Kaltner   18   
18190       18190  245569            L. Watkins   18   
18191       18191  245570  J. Norville-Williams   18   
18192       18192  245571             S. Squire   18   
18193       18193  244823            N. Fuentes   18   
18194       18194  245862              J. Milli   18   
18195       18195  243582            S. Griffin   18   
18196       18196  238477           K. Fujikawa   19   
18197       18197  246167            D. Holland   18   
18198       18198  242844            J. Livesey   18   
18199       18199  244677          M. Baldisimo   18   
18200       18200  231381              J. Young   18   
18201       18201  243413              D. Walsh   18   
18202       18202  238813          J. Lundstram   19   
18203       18203  243165    N. Christoffersson   19   
18204       18204  241638             B. Worman   16   
18205       18205  246268        D. Walker-Rice   17   
18206       18206  246269             G. Nugent   16   

                                                Photo          Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png            Argentina   
1       https://cdn.sofifa.org/players/4/19/20801.png             Portugal   
2      https://cdn.sofifa.org/players/4/19/190871.png               Brazil   
3      https://cdn.sofifa.org/players/4/19/193080.png                Spain   
4      https://cdn.sofifa.org/players/4/19/192985.png              Belgium   
5      https://cdn.sofifa.org/players/4/19/183277.png             

In [183]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
Unnamed: 0                  18207 non-null int64
ID                          18207 non-null int64
Name                        18207 non-null object
Age                         18207 non-null int64
Photo                       18207 non-null object
Nationality                 18207 non-null object
Flag                        18207 non-null object
Overall                     18207 non-null int64
Potential                   18207 non-null int64
Club                        17966 non-null object
Club Logo                   18207 non-null object
Value                       18207 non-null object
Wage                        18207 non-null object
Special                     18207 non-null int64
Preferred Foot              18159 non-null object
International Reputation    18159 non-null float64
Weak Foot                   18159 non-null float64
Skill Moves                 18159 non-null fl

In [184]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [185]:
subset = dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0,how='any')
subset.head(5)

Overall  Age  International Reputation  Weak Foot  Skill Moves
0       94   31                       5.0        4.0          4.0
1       94   33                       5.0        4.0          5.0
2       92   26                       5.0        5.0          5.0
3       91   27                       4.0        3.0          1.0
4       91   27                       4.0        5.0          4.0

In [186]:
columns = subset.columns[1:] #eliminamos Overall
columns

Index(['Age', 'International Reputation', 'Weak Foot', 'Skill Moves'], dtype='object')

In [187]:
players = torch.tensor(subset.values).float()
players

tensor([[94., 31.,  5.,  4.,  4.],
        [94., 33.,  5.,  4.,  5.],
        [92., 26.,  5.,  5.,  5.],
        ...,
        [47., 16.,  1.,  3.,  2.],
        [47., 17.,  1.,  3.,  2.],
        [46., 16.,  1.,  3.,  2.]])

In [188]:
players.shape,players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [189]:
data = players[:,1:] #borramos el resultado, o sea el target
data,data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [190]:
target = players[:,0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [191]:
mean = torch.mean(data,dim=0) # media de las columnas
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [192]:
std = torch.std(data,dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [193]:
#normalizamos
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [194]:
#separamos los datos de los jugadores
good = data[torch.ge(target,85)]
average = data[torch.gt(target,70) & torch.lt(target,85)]
bad = data[torch.lt(target,70)]

In [195]:
goodMean = torch.mean(good,dim=0) #los mejores jugadore
averageMean = torch.mean(average,dim=0) #los maso
badMean = torch.mean(bad,dim=0) #los malos

goodMean, averageMean, badMean

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([24.1909,  1.0079,  2.8795,  2.1952]))

In [196]:
for i, args in enumerate(zip(columns,goodMean,averageMean,badMean)): 
    print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.19
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.88
Skill Moves                 3.04   2.75   2.20
